### ISSUE TITLE
2025 checked release — progress tracker

### ISSUE THREAD

**Issue by basille** [cran-task-views/Tracking#76]
## Tracking CTV 2025-02-12
([details for full process](https://github.com/cran-task-views/Tracking/issues/50))

- [x] Publish a rolling release
- [x] Branch out from `main` into `dev`
- [x] Check all [open issues for package submissions](https://github.com/cran-task-views/Tracking/issues?q=is%3Aissue+is%3Aopen+label%3Aadd-pkg), and make sure submitted packages are sorted out and included in [`Tracking_tbl.csv`](https://github.com/cran-task-views/Tracking/blob/main/checks/Tracking_tbl.csv)
- [x] Run the [full tests](https://github.com/cran-task-views/Tracking/blob/main/CheckPackages.R)
- [x] Complete the [`NEWS.md`](https://github.com/cran-task-views/Tracking/blob/main/NEWS.md) file fully
- [x] Complete and close all open issues.
- [x] Fully update [`Tracking.md`](https://github.com/cran-task-views/Tracking/blob/main/Tracking.md) with new and removed packages.
- [x] Merge `dev` back into `main` and delete the `dev` branch.

**Comment by basille** [comment]
Tracking CTV 2025-02-12 released.
