### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by rociojoo** [cran-task-views/Tracking#8]
## Markdown CTV file

- [ ] **Rewrite the _Path reconstruction_ section** by being more explicit, and check other sections that need clarification (it's OK to have several aims for 1 package, 1 aim for several packages, but not several aims for several packages).

## Long term organisation

- [ ] **Add individual issues for each package of the list**, so we have one place for all discussion points related to a package. We could certainly have templates for basic messages (for instance those that are on CRAN or checks CRAN tests).
- [ ] **Consider contacting maintainers of each package** to let them know about the CTV and their individual issue for relevant discussion.

## Dev features

- [ ] Use **GitHub Actions for continuous integration** of the CTV (just like a R package). That would allow to automatically test current packages. New packages would only be tested when formally added. See [here](https://github.com/r-lib/actions) for relevant examples.
- [ ] Check **[`renv`](https://rstudio.github.io/renv/)** as a replacement to `packrat` to deal with the private library of packages. [Migration tools](https://rstudio.github.io/renv/articles/renv.html#migrating-from-packrat) are provided with `renv`.
- [ ] Implement automatic CRAN package search in our workflow, for instance with `pkgsearch::pkg_search()`, fixing some search terms (#33).

**Comment by rociojoo** [comment]
<a href="https://github.com/rociojoo"><img src="https://avatars.githubusercontent.com/u/18192913?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rociojoo](https://github.com/rociojoo)**
_Wednesday Jul 15, 2020 at 21:58 GMT_

----

I was about to do that but... rsMove was removed from CRAN yesterday. I'll remove it from the ctv, add a comment on the Tracking_tbl.csv about it, push and send the ctv.

**Comment by rociojoo** [comment]
<a href="https://github.com/rociojoo"><img src="https://avatars.githubusercontent.com/u/18192913?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rociojoo](https://github.com/rociojoo)**
_Tuesday Jul 21, 2020 at 17:20 GMT_

----

Notes for future self:
1) Update the date of the CTV version
2) Update the reference to the Joo et al. paper
3) Submit issues on eye and mouse packages if relevant:
- mousetrap https://cran.r-project.org/web/packages/mousetrap
- eyelinker https://cran.r-project.org/web/packages/eyelinker
- eyetracking https://cran.r-project.org/web/packages/eyetracking/index.html
- gazepath https://cran.r-project.org/web/packages/gazepath/index.html
- mousetrack https://cran.r-project.org/web/packages/mousetrack/index.html
- saccades https://cran.r-project.org/web/packages/saccades/index.html
- (eyetrackingR has been deprecated on CRAN in 2020-07)

4) Check pathroutr https://github.com/jmlondon/pathroutr/
5) Check track2kba https://github.com/BirdLifeInternational/track2kba
6) Check actel https://github.com/hugomflavio/actel
7) Check RSP https://github.com/YuriNiella/RSP
8) Check migflow https://github.com/KiranLDA/migflow
9) Check PAMLr https://github.com/KiranLDA/PAMLr
10) Check BaBA https://github.com/wx-ecology/BaBA
11) Check smoove https://github.com/EliGurarie/smoove
12) Check nestR https://github.com/picardis/nestR
13) Check vmsbase https://cran.r-project.org/web/packages/vmsbase/index.html

**Comment by rociojoo** [comment]
<a href="https://github.com/basille"><img src="https://avatars.githubusercontent.com/u/4000337?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [basille](https://github.com/basille)**
_Wednesday Mar 02, 2022 at 10:41 GMT_

----

Other things to consider:

* Use **GitHub Actions for continuous integration** of the CTV (just like a R package). That would allow to automatically test current packages. New packages would only be tested when formally added. See [here](https://github.com/r-lib/actions) for relevant examples.
* Check **[pak](https://pak.r-lib.org/)** as an alternative to `packrat` to deal with the private library of packages. `pak` seems to download and install packages faster, but the benefits might not be that great if packages installs are run serially (instead of parallel install).

**Comment by rociojoo** [comment]
<a href="https://github.com/basille"><img src="https://avatars.githubusercontent.com/u/4000337?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [basille](https://github.com/basille)**
_Monday Mar 07, 2022 at 16:26 GMT_

----

Continued:

* **Add individual issues for each package of the list**, so we have one place for all discussion points related to a package. We could certainly have templates for basic messages (for instance those that are on CRAN or checks CRAN tests).
* **Consider contacting maintainers of each package** to let them know about the CTV and their individual issue for relevant discussion.

**Comment by basille** [comment]
Update.

**Comment by basille** [comment]
Update.

**Comment by basille** [comment]
Moved to [TODO.md](https://github.com/cran-task-views/Tracking/blob/main/TODO.md) for smoother tracking.
